# Generated by Django 4.2.7 on 2025-09-24 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('campay', 'CamPay Mobile Money'), ('wallet', 'Wallet Balance'), ('cash', 'Cash Payment'), ('mtn_momo', 'MTN Mobile Money Direct'), ('orange_money', 'Orange Money Direct')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='name',
            field=models.CharField(choices=[('campay', 'CamPay Mobile Money'), ('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentwebhook',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentwebhook',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='paymentwebhook',
            name='provider',
            field=models.CharField(choices=[('campay', 'CamPay'), ('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_reference'], name='payments_pa_payment_87c4c1_idx'),
        ),
    ]
