# Generated by Django 5.2.6 on 2025-11-17 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemconfig',
            old_name='sms_api_key',
            new_name='twilio_account_sid',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='notify_low_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='notify_order_cancelled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='notify_order_placed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='notify_order_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='notify_payment_success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='backup_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='backup_retention',
            field=models.IntegerField(default=30, help_text='Days'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='cancellation_window',
            field=models.IntegerField(default=10, help_text='Minutes before order can be cancelled'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='from_email',
            field=models.EmailField(default='noreply@canteen.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='lockout_duration',
            field=models.IntegerField(default=15, help_text='Minutes'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='log_level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='log_retention',
            field=models.IntegerField(default=30, help_text='Days'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='order_processing_time',
            field=models.IntegerField(default=15, help_text='Average time in minutes'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='payment_timeout',
            field=models.IntegerField(default=120, help_text='Seconds'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='session_timeout',
            field=models.IntegerField(default=60, help_text='Minutes'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='sms_from_number',
            field=models.CharField(blank=True, help_text='E.164 format: +237XXXXXXXXX', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='sms_provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('nexmo', 'Nexmo/Vonage'), ('local', 'Local Provider')], default='twilio', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='smtp_server',
            field=models.CharField(default='smtp.gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='timezone',
            field=models.CharField(default='Africa/Douala', max_length=50),
        ),
        migrations.AlterModelTable(
            name='systemconfig',
            table='system_config',
        ),
    ]
