# Generated by Django 5.2.6 on 2025-09-28 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_create_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
