# Generated by Django 5.2.6 on 2025-09-29 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_usernotification_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
