# Generated by Django 5.2.6 on 2025-09-27 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_created_by_and_more'),
        ('orders', '0003_order_actual_prep_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
